myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns = [
    path('profile/',views.profile,name="profile"),
]

p9/urls.py
from django.contrib import admin
from django.urls import path,include
import myapp
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/',views.base,name="base"),
    path('',views.home,name="home"),
    path('myapp/',include("myapp.urls")),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def base(request):
    return render(request,"base.html")
def home(request):
    return render(request,"myapp/home.html")
def profile(request):
    name="shanu"
    return render(request,"myapp/profile.html",{'name':name})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>BASE PAGE</title>
    {% endblock %}

<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</head>
<body>
    {% include "partials/_topbar.html" %}
    {% include "partials/_navbar.html" %}
    
        {% block content %}
            <div class="cantainer">
                <div class="jumbotron">
                    <h1>welcome to base page</h1>
                    <img src="{% static 'images/child.jpg' %}" alt="No image found" height="50" width="100">
                    <img src="{% static 'images/flower3.jpg' %}" alt="No image found" height="50" width="100">
                    
                </div>
            </div>
        {% endblock %}
        {% include "partials/_footer.html" %}
</body>
</html>

templates/myapp/home.html
{% extends "base.html" %}

{% block title %}
    <title>Home page</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>welcome to home page</h1>
        </div>
    </div>
{% endblock %}

templates/myapp/profile.html
{% extends "base.html" %}

{% block title %}
    <title>profile page</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>welcome to {{name}} Profile page</h1>
        </div>
    </div>
{% endblock %}

templates/partials/_footer.html
{% extends "base.html" %}

{% block title %}
    <title>profile page</title>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>welcome to {{name}} Profile page</h1>
        </div>
    </div>
{% endblock %}

templates/partials/_navbar.html
<!----navbar---->
<div class="container">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:profile' %}">Profile</a>
        </li>
    </ul>
</div>

templates/partials/_topbar.html
<!----top bar---->
<div class="alert alert-secondary" role="alert">
    <center>TOP BAR</center>
</div>